CXX = g++

Ordonnanceur: main.o Conteneur.o TacheAperiodique.o Conteneur.o TachePeriodique.o Parseur.o Ordonnanceur.o
	$(CXX) -o Ordonnanceur $^
	
Conteneur: Conteneur.hpp Conteneur.cpp TachePeriodique.hpp TacheAperiodique.hpp common.h
	$(CXX) -c Conteneur.cpp -o Conteneur.o
	
TacheAperiodique.o: TacheAperiodique.hpp TacheAperiodique.cpp Tache.hpp common.h
	$(CXX) -c TacheAperiodique.cpp -o TacheAperiodique.o
	
TachePeriodique.o: TachePeriodique.hpp TachePeriodique.cpp Tache.hpp common.h
	$(CXX) -c TachePeriodique.cpp -o TachePeriodique.o
	
Parseur.o: Parseur.cpp Parseur.hpp ConteneurTacheAperiodique.hpp ConteneurTachePeriodique.hpp common.h
	$(CXX) -c Parseur.cpp -o Parseur.o
	
Ordonnanceur.o: Ordonnanceur.hpp Ordonnanceur.cpp ConteneurTachePeriodique.hpp ConteneurTacheAperiodique.hpp common.h
	$(CXX) -c Ordonnanceur.cpp -o Ordonnanceur.o
	
	
	
clean:
	-rm -rf *.o
